<?php

declare(strict_types=1);

namespace Waaseyaa\Routing;

use Waaseyaa\Access\RedirectValidator;

/**
 * Builds fail-closed local and named-route redirect responses.
 *
 * Inject this service into a plain controller when inheritance is not wanted.
 *
 * @api
 */
final readonly class Redirector
{
    /** @internal Request attribute shared by the HTTP kernel and app-controller dispatcher. */
    public const string REQUEST_ATTRIBUTE = '_waaseyaa_redirector';

    private RedirectValidator $validator;

    public function __construct(
        private WaaseyaaRouter $router,
        ?RedirectValidator $validator = null,
    ) {
        $this->validator = $validator ?? new RedirectValidator();
    }

    /**
     * Redirect to a safe local absolute path.
     *
     * @param array<string, string> $headers
     */
    public function to(string $path, int $status = 302, array $headers = []): RedirectResponse
    {
        if (!$this->validator->isSafe($path)) {
            throw new \InvalidArgumentException('Redirect target must be a safe local absolute path.');
        }

        return new RedirectResponse($path, $status, $headers);
    }

    /**
     * Redirect to a named route generated by the request's complete router.
     *
     * @param array<string, mixed> $parameters
     * @param array<string, string> $headers
     */
    public function toRoute(
        string $name,
        array $parameters = [],
        int $status = 302,
        array $headers = [],
    ): RedirectResponse {
        return $this->to($this->router->generate($name, $parameters), $status, $headers);
    }
}
